export const EVENT_COLUMN_CHANGED = 'EVENT_COLUMN_CHANGED'
export const EVENT_DIRECTION_CHANGED = 'EVENT_DIRECTION_CHANGED'
export const EVENT_HEADER_CELL_CLICKED = 'EVENT_HEADER_CELL_CLICKED'
export const EVENT_SIZE_CHANGED = 'EVENT_SIZE_CHANGED'
export const EVENT_PAGE_CHANGED = 'EVENT_PAGE_CHANGED'

export const SORT_DIRECTION_ASCENDING = 'asc'
export const SORT_DIRECTION_DESCENDING = 'desc'

export const COLUMN_ID = 'Id'
export const COLUMN_NAME = 'Name'
export const COLUMN_NOTES = 'Notes'
export const COLUMN_ORDER_NUMBER = 'Order Number'
export const COLUMN_TEXT = 'Text'
export const COLUMN_PRIORITY = 'Priority'
export const COLUMN_ENTRY = 'Entry'
export const COLUMN_PHRASE = 'Phrase'
export const COLUMN_EXPORTABLE = 'Exportable'
export const COLUMN_TYPE = 'Type'
export const COLUMN_FROM = 'From'
export const COLUMN_DATE = 'Date'
export const COLUMN_SEARCHED = 'Searched'

export const OBJECT_PROPERTY_ID = 'id'
export const OBJECT_PROPERTY_NAME = 'name'
export const OBJECT_PROPERTY_NOTES = 'notes'
export const OBJECT_PROPERTY_ORDER_NUMBER = 'orderNumber'
export const OBJECT_PROPERTY_TEXT = 'text'
export const OBJECT_PROPERTY_PRIORITY = 'priority'
export const OBJECT_PROPERTY_EXPORTABLE = 'exportable'
export const OBJECT_PROPERTY_ENTRY_NAME = 'entryName'
export const OBJECT_PROPERTY_RESULT_TYPE = 'resultType'
export const OBJECT_PROPERTY_CREATION_TIME = 'creationTime'
export const OBJECT_PROPERTY_ABOUT = 'about'


export const CELL_TEMPLATE_INPUT = 'input'
export const CELL_TEMPLATE_TEXTAREA = 'text-area'
export const CELL_TEMPLATE_LINK = 'link'

export const ROW_TEMPLATE_LINK = 'link'